### ISSUE TITLE
Computation time

### ISSUE THREAD

**Issue by BeichenSuVC** [stanislaushimovolos/Intelligent-Scissors#1]
Hi,
    Based on the paper, the time complexity of the algorithm should be O(N). But in practice, it took around 15 seconds to process the image to get the static cost. I am wondering if this is the normal case to process the image.
    Also, did the path cooling and on the fly training included here?
    Thanks for any heads-up.

**Comment by stanislaushimovolos** [comment]
Hi,
The algorithm can process the image in real time. However, my implementation only includes static/dynamic cost and a naive graph search. Are you sure that calculating static features takes so much time? Do you mean graph search? This part is very inefficient now. I am going to improve performance and add additional features within a couple of weeks.

**Comment by BeichenSuVC** [comment]
`import pickle
import numpy as np
from collections import deque
from scipy.ndimage.filters import gaussian_filter1d
from skimage.filters import gaussian, laplace, sobel_h, sobel_v, sobel
import skimage
import time
from PIL import Image, ImageDraw
from scissors.graph import PathFinder
from scissors.feature_extraction import StaticExtractor, DynamicExtractor, Scissors
t1 = time.time()
image_path = 'Image.jpg'
image = Image.open(image_path)

t2 = time.time()
w,h = image.size
gray_scaled = skimage.color.rgb2gray(np.asarray(image))
static_extractor = StaticExtractor()
static_cost = static_extractor(gray_scaled)

t3 = time.time()
finder = PathFinder(image.size, static_cost)

t4 = time.time()
dynamic_extractor = DynamicExtractor()
dynamic_features = dynamic_extractor(gray_scaled)
scissors = Scissors(static_cost, dynamic_features, finder)
t5 = time.time()
    
print('t2-t1:',t2-t1)
print('t3-t2:',t3-t2)
print('t4-t3:',t4-t3)
print('t5-t4:',t5-t4)`

t2-t1: 0.011044979095458984
t3-t2: 0.4484446048736572
t4-t3: 14.301629066467285
t5-t4: 0.20930242538452148

Right, the graph search took the most of the time.

**Comment by BeichenSuVC** [comment]
The Pather Finder here is an O(N^2) forloop, should be much fast with the unrestricted graph search.

**Comment by stanislaushimovolos** [comment]
Thanks for your reply. There's still a lot of work to do. You may look at GIMP implementation of this tool. It works in real time and includes a lot of additional features.
